services:
  ecommerce-db:
    image: postgres:16-alpine
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d product_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  product-api:
    build:
      context: .
      dockerfile: src/ProductService/ProductService.Api/Dockerfile
    container_name: product-api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__DefaultConnection: Host=ecommerce-db;Port=5432;Database=product_db;Username=postgres;Password=postgres
    ports:
      - "5001:8080"
    depends_on:
      ecommerce-db:
        condition: service_healthy
    networks:
      - ecommerce-network

  order-api:
    build:
      context: .
      dockerfile: src/OrderService/OrderService.Api/Dockerfile
    container_name: order-api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__DefaultConnection: Host=ecommerce-db;Port=5432;Database=order_db;Username=postgres;Password=postgres
      ProductServiceUrl: http://product-api:8080
      ASPNETCORE_HTTP_PORTS: 8080
    ports:
      - "5002:8080"
    depends_on:
      ecommerce-db:
        condition: service_healthy
      product-api:
        condition: service_started
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres-data:
